#####################################################################
# Makefile for IPNS binary to ascii conversion program
#####################################################################

CC  = gcc
F77  =  g77
CCFLAGS  = -O -w
FFLAGS  = -O -w
LDFLAGS =

INSTALL_DIR = ../../binary
INSTALL_MOD = 755

OBJC_BTOA = sepdbtoa.o
OBJC_INFO = sepdinfo.o
OBJF = asc2plot.o 

.f.o:
	$(F77) -c $(FFLAGS) $<

all: sepdbtoa.exe sepdinfo.exe asc2plot.exe

sepdbtoa.exe: $(OBJC_BTOA)
	$(CC) -o sepdbtoa.exe $(OBJC_BTOA) $(LDFLAGS)

sepdinfo.exe: $(OBJC_INFO)
	$(CC) -o sepdinfo.exe $(OBJC_INFO) $(LDFLAGS)

asc2plot.exe: $(OBJF)
	$(F77) -o asc2plot.exe $(OBJF) $(LDFLAGS)

install: sepdbtoa.exe sepdinfo.exe asc2plot.exe
	cp *.exe $(INSTALL_DIR)

clean: 
	rm -f *~ *.exe *.o

